<?php if(!defined('KIRBY')) exit ?>

title: Site
pages:
  template:
    - default
    - buildings
    - events
fields:
  siteSettings:
    label: Site Settings
    type:  headline
  title:
    label: Title
    type:  title
  author:
    label: Author
    type:  text
  description:
    label: Description
    type:  textarea
  keywords:
    label: Keywords
    type:  tags
